pretrained_model_name_or_path: "runwayml/stable-diffusion-v1-5"
placeholder_token_init_mode: "mean_emb_cov_emb"
resolution: 384 
scale_lr: True
guidance_scale: 7
validation_steps: 50 
dataloader_num_workers: 0 
num_inference_steps: 5
mixed_precision: "bf16" 
report_to: wandb
only_save_embeds: True 
save_steps: 250  
dataset: "waterbirds" 
gradient_accumulation_steps: 1 
learning_rate: 0.04 
lr_scheduler: "linear" 
lr_warmup_steps: 0 
adam_weight_decay: 0 
strength: 1.0 
train_batch_size: 10 
num_new_tokens: 5
skip_adv_loss_steps: 30 
max_train_steps: 1000
num_images: 10 
wandb_group: "waterbirds-advopt" 
wandb_name: "advopt" 
good_logging: false
## mask
paste_masked_pixels: false

train_data_dir: ???
